#+TITLE: Event Registration
#+AUTHOR: Hao Xiang Liew

* [[https://github.com/haoxiangliew/event-registration][event-registration]]
This is a custom app for Virgnia Tech student organizations to take in a spreadsheet and confirm the scanned individual is registered.

** Installation
*** Linux
#+BEGIN_SRC sh
python3 -m venv ./venv
source ./venv/bin/activate<.fish>
pip3 install -r requirements.txt
python3 main.py
#+END_SRC
*** Windows
- TODO
- Or use WSL

** Specifications
*** Scanner
- The scanner is sourced from thesource@vt.edu
  - [[https://store-scantec.com/Search/ProductView.aspx?partid=222567983][Scan Technology Inc. 4000M-DBU6]]
    - Scanning an ID results with the following as USB keyboard input:
      #+BEGIN_SRC sh
      ;<"9-digit ID">=0249?

      #+END_SRC
    - Scanner can be inaccurate at times, note scanning speed can't be too fast or too slow.
*** IDs
- 9-digits.
- Presume the last 4-digits are unique.
  - If for some edge case, there are duplicate IDs, prompt for a name search of those entries.
*** Application
**** Dependencies
#+BEGIN_SRC sh
openpyxl
pandas
tkinter
#+END_SRC
- Takes in ~input.xlsx~, with the first-row as categories.
  - Should have no duplicate ID and names.
- Filter input for scanner and manual input automatically.
- ~tkinter~ popups can be dismissed quickly with ~<RET>~.
