#+TITLE: Event Registration
#+AUTHOR: Hao Xiang Liew

* [[https://github.com/haoxiangliew/event-registration][event-registration]]
This is a custom app for Virgnia Tech student organizations to take in a spreadsheet and confirm the scanned individual is registered.

App was made specifically for [[https://ieee.vt.edu][IEEE@VT]]'s Happy Hour, hello there!

** Installation
*** Prerequisites
- [[https://www.python.org/downloads/][Python 3+]]
- Make sure Python is configured for [[https://tkdocs.com/tutorial/install.html][TKinter]]
  - Linux: Search your repositories for python-tk / tkinter
  - Windows: Official Distribution
  - MacOS: Official Distribution / ~brew install python-tk~ (Homebrew)
*** Linux
#+BEGIN_SRC sh
  python3 -m venv ./venv
  source ./venv/bin/activate
  pip3 install -r requirements.txt
  python3 main.py
#+END_SRC
*** Windows
#+BEGIN_SRC sh
  python -m venv ./venv
  .\venv\Scripts\Activate.ps1
  pip install -r requirements.txt
  python main.py
#+END_SRC
*** MacOS
Using the shell, the Linux instructions should work perfectly

** Specifications
*** Scanner
- The scanner is sourced from thesource@vt.edu
  - [[https://store-scantec.com/Search/ProductView.aspx?partid=222567983][Scan Technology Inc. 4000M-DBU6]]
    - Scanning an ID results with the following as USB keyboard input:
      #+BEGIN_SRC sh
        ;["9-digit ID"]=0249?
        ["\n"]
      #+END_SRC
    - Scanner can be inaccurate at times, note scanning speed can't be too fast or too slow.
*** IDs
- 9-digits.
- Presume the last 4-digits are unique.
  - If for some edge case, there are duplicate IDs, prompt for a name search of those entries.
*** Application
**** Dependencies
#+BEGIN_SRC sh
  openpyxl
  pandas
  tk
#+END_SRC
- Takes in ~input.xlsx~, with the first-row as categories.
  - Should have no duplicate ID and names.
- Filter input for scanner and manual input automatically.
- ~tkinter~ popups can be dismissed quickly with ~<RET>~.
